### ISSUE TITLE
Trying to deploy on RPI3

### ISSUE THREAD

**Issue by ZJaume** [NoMore201/playmaker#17]
I'm trying to deploy playmaker on my rpi3 and the fdroid server can't initialize ("Error while executing fdroidserver tool"). Where can I find the log to search the problem?

**Comment by NoMore201** [comment]
There is no logging feature (yet), all debug information is written on stdout.

Anyway, the problem seems to be clear: you didn't install the fdroidserver tool [1]. If you want to deploy it without docker, as specified in README, you need to install fdroidserver and the Android SDK. Even if you don't know how to use docker, you can read the Dockerfile as a "guide" to setup.

[1] https://github.com/NoMore201/playmaker#virtualenv
